name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xclip

    - name: Install build dependencies
      run: make deps

    - name: Verify dependencies
      run: make tidy

    - name: Build
      run: make build

    - name: Run tests (excluding emulator tests)
      run: make test-short

    - name: Run coverage (excluding emulator tests)
      run: |
        go test -v -race -coverprofile=coverage-pkg.out -short ./pkg/...
        go test -v -race -coverprofile=coverage-internal.out -short ./internal/...
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage-pkg.out,./coverage-internal.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  emulator-test:
    runs-on: ubuntu-latest
    # Only run emulator tests on main branch pushes or when manually triggered
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Install build dependencies
      run: |
        make deps
        # Install C++ compiler for bigquery emulator
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Run emulator tests
      run: make test-emulator
      continue-on-error: true  # Don't fail CI if emulator tests have issues

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Build binary
      run: make build-all

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bqui-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/