name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xclip

    - name: Install build dependencies
      run: make deps

    - name: Verify dependencies
      run: make tidy

    - name: Build
      run: make build

    - name: Run tests (excluding emulator tests)
      run: make test-short

    - name: Run coverage (excluding emulator tests)
      run: |
        go test -v -race -coverprofile=coverage-pkg.out -short ./pkg/...
        go test -v -race -coverprofile=coverage-internal.out -short ./internal/...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage-pkg.out,./coverage-internal.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  emulator-test:
    runs-on: ubuntu-latest
    # Only run emulator tests on main branch pushes or when manually triggered
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Install build dependencies
      run: |
        make deps
        # Install C++ compiler for bigquery emulator
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Run emulator tests
      run: make test-emulator
      continue-on-error: true  # Don't fail CI if emulator tests have issues

  build:
    needs: test
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            runs-on: ubuntu-latest
          - goos: linux
            goarch: arm64
            runs-on: ubuntu-latest
          - goos: darwin
            goarch: amd64
            runs-on: macos-latest
          - goos: darwin
            goarch: arm64
            runs-on: macos-latest
          - goos: windows
            goarch: amd64
            runs-on: windows-latest
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: make deps

    - name: Build binary for specific platform
      run: |
        mkdir -p build
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w" -o build/bqui$(if [ "${{ matrix.goos }}" = "windows" ]; then echo ".exe"; fi) ./cmd/bqui
      shell: bash

    - name: Upload artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: bqui-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/
